# Generated by Django 5.0.4 on 2024-04-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Centralsection',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centers_departments.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='images/centers_departments/centralsection')),
                ('status', models.CharField(max_length=150)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Central section',
                'verbose_name_plural': 'Central sections',
            },
            bases=('centers_departments.basemodel',),
        ),
        migrations.CreateModel(
            name='Departmenthistory',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centers_departments.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='images/centers_departments/departmenthistory')),
                ('status', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmen_thistory', to='centers_departments.centralsection')),
            ],
            options={
                'verbose_name': 'Department history',
                'verbose_name_plural': 'Department historys',
            },
            bases=('centers_departments.basemodel',),
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centers_departments.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='images/centers_departments/members')),
                ('birth_date', models.IntegerField()),
                ('status', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('academic_degree', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='centers_departments.centralsection')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
            bases=('centers_departments.basemodel',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centers_departments.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('base_file', models.FileField(blank=True, null=True, upload_to='images/centers_departments/picture')),
                ('image', models.ImageField(upload_to='images/centers_departments/picture')),
                ('status', models.CharField(max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='centers_departments.centralsection')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
            bases=('centers_departments.basemodel',),
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centers_departments.basemodel')),
                ('title', models.CharField(max_length=250)),
                ('base_file', models.FileField(blank=True, null=True, upload_to='images/centers_departments/research')),
                ('content', models.TextField()),
                ('status', models.CharField(max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research', to='centers_departments.centralsection')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researchs',
            },
            bases=('centers_departments.basemodel',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centers_departments.basemodel')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/centers_departments/video')),
                ('status', models.CharField(max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('center_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='centers_departments.centralsection')),
            ],
            bases=('centers_departments.basemodel',),
        ),
    ]
